---
title: "The Impact of Hispanic Last Names on Educational and Labor Market Outcomes"
date: 2025-08-23
published-title: "Published online"
description: "People likely to have Hispanic surnames complete 0.39 fewer years of education, and men earn 5 percentage points less, than otherwise similar children of interethnic couples."
author:
  - name: Hussain Hadah
    url: https://www.hussainhadah.com/
    orcid: 0000-0002-8705-6386
    affiliation: Northwestern University
categories:
  - Discrimination
  - Identity and Immigration
  - Education
  - Labor
pub-info:
  authors: <strong>Hussain Hadah</strong>
  venue: >-
    <em>Journal of Economics, Race, and Policy</em>, published online 2025; 9(1), 1–11 (2026). doi: <a href="https://doi.org/10.1007/s41996-025-00177-3"><code>10.1007/s41996-025-00177-3</code></a>.
  links:
    - name: Preprint
      url: https://dx.doi.org/10.2139/ssrn.4566234
      icon: bi bi-file-earmark-pdf
      local: false
    - name: Final version
      url: https://doi.org/10.1007/s41996-025-00177-3
      icon: bi bi-journal-text
    - name: Code
      url: https://github.com/hhadah/hispanic-last-names.git
      icon: bi bi-github
    - name: Data
      url: https://github.com/hhadah/hispanic-last-names/tree/main/data
      icon: bi bi-table
doi: 10.1007/s41996-025-00177-3
---


## Important links

- [Paper (preprint)](https://dx.doi.org/10.2139/ssrn.4566234)

## Abstract

Do individuals with Hispanic surnames face discrimination in access to education and the labor market? This study analyzes the impact of likely Hispanic surnames on wages among Americans with one White and one Hispanic parent. Individuals who likely have Hispanic surnames (i.e. those with a Hispanic father) often complete less education and earn less, with a notable wage gap favoring those with white-sounding surnames. People born to Hispanic fathers and White mothers receive 0.39 fewer years of education than those born to White fathers and Hispanic mothers. Men born to Hispanic fathers and White mothers earn 5 percentage points less than those born to White fathers and Hispanic mothers, and they are 1 percentage point more likely to be unemployed. I also show that this gap can be largely explained by educational differences.

## Citation

Hadah, Hussain. "The Impact of Hispanic Last Names on Educational and Labor Market Outcomes." *Journal of Economics, Race, and Policy*, published online August 23, 2025; 9(1): 1–11 (2026). https://doi.org/10.1007/s41996-025-00177-3.

```bibtex
@article{hadah2025effect,
    author = {Hadah, Hussain},
    title = {The Impact of Hispanic Last Names on Educational and Labor Market Outcomes},
    journal = {Journal of Economics, Race, and Policy},
    year = {2026},
    volume = {9},
    number = {1},
    pages = {1--11},
    doi = {10.1007/s41996-025-00177-3}
}
```