---
title: "Democracy and Ethnic Favoritism: Evidence from Africa"
description: "Evidence of ethnic favoritism is mixed overall but stronger within the democracy-only and anocracy-only samples."
order: 10
author:
  - name: Hussain Hadah
    url: https://www.hussainhadah.com/
    orcid: 0000-0002-8705-6386
    affiliation: Northwestern University
  - name: Bariş Alan&ast;
categories:
  - Political Economy and Institutions
pub-info:
  authors: <strong>Hussain Hadah</strong> and Bariş Alan&ast;
  venue: <em>Under review</em>.
  links:
    - name: Preprint
      url: "https://dx.doi.org/10.2139/ssrn.4566225"
      icon: bi bi-file-earmark-pdf
      local: false
    - name: Code
      url: https://github.com/hhadah/ethnicfavoritism.git
      icon: bi bi-github
    - name: Data
      url: https://github.com/hhadah/ethnicfavoritism/tree/main/data/raw
      icon: bi bi-table
  extra: >-
    Presented at the 2021 Southern Economic Association.
---

## Important links

- [Paper (preprint)](https://dx.doi.org/10.2139/ssrn.4566225)

## Abstract

What is the effect of democracy on ethnic favoritism? I estimate the relationship between co-ethnicity and five outcomes of public good provision – education, infant health,
wealth, access to clean drinking water and access to electricity – using data from twentyone African countries. Following previous research, I use variation in co-ethnicity across
ethnic groups and over time. I first estimate the relationship between these five outcomes and co-ethnicity in the full sample and then split the analysis between anocracies and democracies. I find mixed evidence of ethnic favoritism in the full sample. I find more evidence of co-ethnic targeting when comparing within democracies only and
within anocracies only.

## Citation

Hadah, Hussain, Democracy and Ethnic Favoritism: Evidence from Africa (September 8, 2023). Available at SSRN: https://ssrn.com/abstract=4566225 or http://dx.doi.org/10.2139/ssrn.4566225

```bibtex
@article{hadah2023ethnicfav,
    Author = {Hadah, Hussain AND Alan, Bariş},
    Title = {Democracy and Ethnic Favoritism: Evidence from Africa},
    Year = {2023}}
```