---
title: "Urban Economics"
description: "A review of the determinants of the location, size, growth, and form of urban areas. Study of the major issues of contemporary urban life: physical deterioration, growth of ghettos, congestion, pollution, transportation, and land use."
---

# Tulane University

## Spring 2024
### Urban Economics
A review of the determinants of the location, size, growth, and form of urban areas. Study of the major issues of contemporary urban life: physical deterioration, growth of ghettos, congestion, pollution, transportation, and land use.

You can find the syllabus [here](https://hhadah.github.io/urban-econ/syllabus/UrbanEcon3320SyllabusSpring2024HHadah.pdf).

#### Slides

1. Class 1: Introduction \[[**.html**](https://hhadah.github.io/urban-econ/slides/01-week1/01-class01/01-class1.html) | [**.pdf**](https://hhadah.github.io/urban-econ/slides/01-week1/01-class01/01-class1.pdf)\]

2. Class 2: Geographical Definitions and Data \[[**.html**](https://hhadah.github.io/urban-econ/slides/01-week1/02-class/02-class2.html) | [**.pdf**](https://hhadah.github.io/urban-econ/slides/01-week1/02-class/02-class2.pdf)\]


3. Class 3: Agglomeration, Clusters, and Cities \[[**.html**](https://hhadah.github.io/urban-econ/slides/01-week1/03-class/01-class3.html) | [**.pdf**](https://hhadah.github.io/urban-econ/slides/01-week1/03-class/01-class3.pdf)\]

4. Class 4: Practice Jigsaw Activity \[[**.html**](https://hhadah.github.io/urban-econ/slides/02-week2/01-class/01-class.html) | [**.pdf**](https://hhadah.github.io/urban-econ/slides/02-week2/01-class/01-class.pdf)\]

5. Class 5: Overview of Greenstone, Hornbeck, and Moretti (2010) \[[**.html**](https://hhadah.github.io/urban-econ/slides/02-week2/02-class/02-class.html) | [**.pdf**](https://hhadah.github.io/urban-econ/slides/02-week2/02-class/02-class.pdf)\]


6. Class 6: Reading Results Tables \[[**.html**](https://hhadah.github.io/urban-econ/slides/03-week3/01-class/01-class2.html) | [**.pdf**](https://hhadah.github.io/urban-econ/slides/03-week3/01-class/01-class2.pdf)\]

7. Class 7: Economic Development Incentives  \[[**.html**](https://hhadah.github.io/urban-econ/slides/03-week3/02-class/01-class01.html) | [**.pdf**](https://hhadah.github.io/urban-econ/slides/03-week3/02-class/01-class01.pdf)\]


8. Class 8: Introduction to Economics of Crime  \[[**.html**](https://hhadah.github.io/urban-econ/slides/04-week4/02-class/crime-intro.html) | [**.pdf**](https://hhadah.github.io/urban-econ/slides/04-week4/02-class/crime-intro.pdf)\]

9. Class 9: Explanation of Common Terminology in Causal Studies in
(Urban) Economics  \[[**.html**](https://hhadah.github.io/urban-econ/slides/04-week4/03-class/causal-term.html) | [**.pdf**](https://hhadah.github.io/urban-econ/slides/04-week4/03-class/causal-term.pdf)\]


<!--
11. Class 11: Effect of Police on Crime & Economic Circumstances on Crime \[[**.html**](https://hhadah.github.io/urban-econ/slides/06-week6/02-thur/police-econ-and-crime.html) | [**.pdf**](https://hhadah.github.io/urban-econ/slides/06-week6/02-thur/police-econ-and-crime.pdf)\]


12. Class 12: Crime and Gender-Based Violence \[[**.html**](https://hhadah.github.io/urban-econ/slides/07-week7/02-thur/gender-based-violence.html) | [**.pdf**](https://hhadah.github.io/urban-econ/slides/07-week7/02-thur/gender-based-violence.pdf)\]

13. Class 13:  Introduction to the Economics of Discrimination \[[**.pdf**](https://hhadah.github.io/urban-econ/slides/08-week8/02-thur/UrbanEconomicsIntrotoDiscrimination.pdf)\]

14. Class 14:  Racial Bias in Policing I \[[**.html**](https://hhadah.github.io/urban-econ/slides/09-week9/01-tue/racial-bias.html) | [**.pdf**](https://hhadah.github.io/urban-econ/slides/09-week9/01-tue/racial-bias.pdf)\]

15. Class 15:  Racial Bias in Policing II \[[**.html**](https://hhadah.github.io/urban-econ/slides/09-week9/02-thur/racial-bias-w.html) | [**.pdf**](https://hhadah.github.io/urban-econ/slides/09-week9/02-thur/racial-bias-w.pdf)\]

16. Class 16:  Criminal Justice and the Labor Market \[[**.html**](https://hhadah.github.io/urban-econ/slides/10-week10/02-thur/incarceration-ban-box.html) | [**.pdf**](https://hhadah.github.io/urban-econ/slides/10-week10/02-thur/incarceration-ban-box.pdf)\]

17. Class 17:  Housing Subsidies \[[**.html**](https://hhadah.github.io/urban-econ/slides/11-housing/01-lecture1/01-housing.html) | [**.pdf**](https://hhadah.github.io/urban-econ/slides/11-housing/01-lecture1/01-housing.pdf)\]

18. Class 18:  Housing Policies I \[[**.pdf**](https://hhadah.github.io/urban-econ/slides/11-housing/02-lecture2/19-HousingPoliciesMetcalfSlides.pdf)\]

19. Class 19:  Housing Policies II \[[**.html**](https://hhadah.github.io/urban-econ/slides/11-housing/03-lecture3/03-housing.html) | [**.pdf**](https://hhadah.github.io/urban-econ/slides/11-housing/03-lecture3/03-housing.pdf)\]

20. Class 20:  Neighborhood Effects \[[**.pdf**](https://hhadah.github.io/urban-econ/slides/11-housing/04-lecture4/21-NeighborhoodEffectsMovingtoOpportunity.pdf)\]

21. Class 21:  Rent Control \[[**.html**](https://hhadah.github.io/urban-econ/slides/11-housing/05-rent-control/rent-control.html) | [**.pdf**](https://hhadah.github.io/urban-econ/slides/11-housing/05-rent-control/rent-control.pdf)\]
-->
