---
title: "About Me"
title-block-banner: "#006747"
page-layout: full
---

I am a labor, health, and education economist currently a postdoctoral fellow at Tulane University's [Department of Economics](https://liberalarts.tulane.edu/departments/economics) and [Murphy Institute](https://murphy.tulane.edu/). My research uses causal inference methods, field experiments, and administrative data to evaluate policies and understand economic behavior across diverse contexts including discrimination, identity formation, peer effects, institutional effectiveness, and public health interventions.

1. **Discrimination against Minorities and Ethnic Identity**

    - I compared the children of inter-ethnic couples to quantify labor and education markets discrimination against people with Hispanic-sounding last names.
    
    - I examined how state-level variation in bias influences Hispanics' decisions to identify with, or not identify, their ethnic minority status.

2. **Quantifying Discrimination Using Audit Field Experiments**

    - In two working papers, I study discrimination using audit field experiments.
    
    - In one audit, we quantify discrimination in access to the mortgage market against same-sex couples and racial minorities.
    
    - In another audit, we study discrimination in access to education, with an emphasis on differences between traditional, private, and charter schools against children who are LGBTQI+, racial minorities, have behavioral issues, or have IEP status.

3. **Applied Microeconomics: Education, Labor, and Health**

    - My applied microeconomics research also includes studying education, labor, and health. This involves analyzing how disparities in access and outcomes across different demographic groups affect labor and education markets, and health outcomes.

    
    - In other research, I explore the impact of peer mental health on individual mental health outcomes, education, and labor market outcomes.
