---
title: "The Impact of Hispanic Last Names and Identity on Educational and Labor Market Outcomes"
# date: 2022-05-01
author:
  - name: Hussain Hadah
    url: http://www.hussainhadah.com/
    orcid: 0000-0002-8705-6386
    affiliation: Tulane University
categories: 
  - Ethnicity
  - Bias
  - Discrimination
pub-info:
  reference: >-
    <strong>Hussain Hadah</strong>, “The Impact of Hispanic Last Names and Identity on Educational and Labor Market Outcomes,” <em>Revise and resubmit at Journal of Economics, Race, and Policy</em>
  links:
    - name: Preprint
      url: https://dx.doi.org/10.2139/ssrn.4566234
      icon: fa-solid fa-file-pdf
      local: false
    - name: Code
      url: https://github.com/hhadah/hispanic-last-names.git
      icon: fab fa-github
    - name: Data
      url: https://github.com/hhadah/hispanic-last-names/tree/main/data
      icon: fas fa-table
# doi: 
---


## Important links

- [Paper (preprint)](https://dx.doi.org/10.2139/ssrn.4566234)

## Abstract

Do individuals with Hispanic names face labor market discrimination? This study analyzes the impact of Hispanic-sounding surnames on wages among inter-ethnic children with one White and one Hispanic parent. I find that individuals with Hispanic surnames often earn less, with a notable wage gap favoring those with White surnames. People born to Hispanic fathers and White mothers receive 0.3 years of education less than those born to White fathers and Hispanic mothers. Males born to Hispanic fathers and White mothers earn 5 percentage points less than those born to White fathers and Hispanic mothers, largely due to educational differences. Additionally, men with Spanish-sounding last names who identify as Hispanic earn significantly less, again due to educational disparities.

## Citation

Hadah, Hussain, The Impact of Hispanic Last Names and Identity on Educational and Labor Market Outcomes (September 3, 2023). Available at SSRN: https://ssrn.com/abstract=4566234 or http://dx.doi.org/10.2139/ssrn.4566234

```bibtex
@article{hadah2022effect:2021,
    Author = {Hadah, Hussain},
    Title = {The Impact of Hispanic Last Names and Identity on Educational and Labor Market Outcomes},
    Year = {2022}}
```