---
title: "The Effect of Racial and Ethnic Attitudes on Hispanic Identity in the U.S."
# date: 2022-11-15
author:
  - name: Hussain Hadah
    url: http://www.hussainhadah.com/
    orcid: 0000-0002-8705-6386
    affiliation: Tulane University
categories: 
  - Ethnicity
  - Bias
  - Discrimination
pub-info:
  reference: >-
    <strong>Hussain Hadah</strong>, “The Effect of Racial and Ethnic Attitudes on Hispanic Identity in the U.S.,” R&R <em>Southern Economic Journal</em>
  links:
    - name: Preprint
      url: https://dx.doi.org/10.2139/ssrn.4566232
      icon: fa-solid fa-file-pdf
      local: false
  extra: >-
    Presented at the 2023 European Society for Population Economics (ESPE) conference and the 93<sup>rd</sup> Southern Economic Association Annual Meeting.
# doi: 
---

## Important links

- [Paper (preprint)](https://dx.doi.org/10.2139/ssrn.4566232)

## Abstract

In this paper, I study the determinants of the choice to identify as Hispanic among
those who could—those whose parents, grandparents, or selves were born in a Spanishspeaking country. I find that individuals with Hispanic ancestry are significantly less
likely to self-identify as Hispanic if they live in states with high levels of implicit ethnic bias. A one standard deviation increase in bias decreases self-reported Hispanic identity by 7-13 percentage points for first and second-generation Hispanics, respectively. These effects are more prominent among second-generation immigrants whose mothers and
fathers were born in a Spanish-speaking country than among children of inter-ethnic
parents. These findings have implications for the interpretation of economic research
on racial and ethnic gaps in a variety of contexts, including labor market outcomes,
redistributive policies, and political representation.

## Citation

Hadah, Hussain, The Effect of Racial and Ethnic Attitudes on Hispanic Identity in the U.S. (August 22, 2023). Available at SSRN: https://ssrn.com/abstract=4566232 or http://dx.doi.org/10.2139/ssrn.4566232

```bibtex
@article{hadah2023hispanicidentity,
    Author = {Hadah, Hussain},
    Title = {The Effect of Racial and Ethnic Attitudes on Hispanic Identity in the U.S.},
    Year = {2023}}
```